Skip report deployment script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,17 +33,17 @@ jobs:
       - name: Sts GetCallerIdentity
         run: |
           aws sts get-caller-identity
-      - name: Install initial tools required by report_deployment_status.sh
-        run: |
-          sudo apt-get update
-          sudo apt-get install jq
-          sudo apt-get install -y httpie
-      - name: Output GH Event Data
-        run: |
-          jq -r . "$GITHUB_EVENT_PATH"
-    #   - name: Deploy dev
+    #   - name: Install initial tools required by report_deployment_status.sh
     #     run: |
-    #       trap 'scripts/report_deployment_status.sh failure' ERR
-    #       scripts/report_deployment_status.sh in_progress "Starting deployment"
-    #       source scripts/init_ci_runner.sh
-    #       make deploy
+    #       sudo apt-get update
+    #       sudo apt-get install jq
+    #       sudo apt-get install -y httpie
+    #   - name: Output GH Event Data
+    #     run: |
+    #       jq -r . "$GITHUB_EVENT_PATH"
+      - name: Deploy dev
+        run: |
+          #trap 'scripts/report_deployment_status.sh failure' ERR
+          #scripts/report_deployment_status.sh in_progress "Starting deployment"
+          source scripts/init_ci_runner.sh
+          make deploy
